language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

branches:
  only:
    - master
    - develop

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - composer test -- --coverage-clover=coverage.xml

cache:
  directories:
    - $HOME/.composer/cache

